"""Add relationships to Subcategory and Blog models

Revision ID: 2159638ab04a
Revises: f44940626417
Create Date: 2024-10-02 18:09:25.001513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2159638ab04a'
down_revision: Union[str, None] = 'f44940626417'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
