"""Add relationships to Subcategory and Blog models

Revision ID: 3ee100b99e81
Revises: 2159638ab04a
Create Date: 2024-10-02 18:17:07.588395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ee100b99e81'
down_revision: Union[str, None] = '2159638ab04a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
